version: '3.9'
services:
  frontend:
      build:
        context: frontend.<%= projectName %>
        target: development
      ports:
        - 3000:3000
      volumes:
        - ./frontend.<%= projectName %>/src:/code/src
        - /code/node_modules